import type { FastifyInstance } from 'fastify';
import { authRoutes } from './auth.routes.js';
import { plaidRoutes } from './plaid.routes.js';
import { twinRoutes } from './twin.routes.js';
import { shareRoutes } from './share.routes.js';
import { institutionRoutes } from './institution.routes.js';
import { chatRoutes } from './chat.routes.js';
import { zkpRoutes } from './zkp.routes.js';
import { badgeRoutes } from './badge.routes.js';
import { insightsRoutes } from './insights.routes.js';
import { optimizerRoutes } from './optimizer.routes.js';
import { timeMachineRoutes } from './timeMachine.routes.js';
import { redFlagsRoutes } from './redFlags.routes.js';
import { attestationRoutes } from './attestation.routes.js';
import { widgetRoutes } from './widget.routes.js';
import { goalsRoutes } from './goals.routes.js';
import { syncRoutes } from './sync.routes.js';
import { partnerRoutes } from './partner.routes.js';
import { notificationRoutes } from './notification.routes.js';
import { identityRoutes } from './identity.routes.js';
import { benchmarkRoutes } from './benchmark.routes.js';
import { negotiateRoutes } from './negotiate.routes.js';
import { wrappedRoutes } from './wrapped.routes.js';
import { env } from '../config/env.js';

export async function registerRoutes(app: FastifyInstance): Promise<void> {
  const prefix = `/api/${env.API_VERSION}`;
  await app.register(authRoutes, { prefix: `${prefix}/auth` });
  await app.register(plaidRoutes, { prefix: `${prefix}/plaid` });
  await app.register(twinRoutes, { prefix: `${prefix}/twin` });
  await app.register(shareRoutes, { prefix: `${prefix}/share` });
  await app.register(institutionRoutes, { prefix: `${prefix}/institution` });
  await app.register(chatRoutes, { prefix: `${prefix}/chat` });
  await app.register(zkpRoutes, { prefix: `${prefix}/zkp` });
  await app.register(badgeRoutes, { prefix: `${prefix}/verify` });
  await app.register(insightsRoutes, { prefix: `${prefix}/insights` });
  await app.register(optimizerRoutes, { prefix: `${prefix}/optimize` });
  await app.register(timeMachineRoutes, { prefix: `${prefix}/time-machine` });
  await app.register(redFlagsRoutes, { prefix: `${prefix}/red-flags` });
  await app.register(attestationRoutes, { prefix: `${prefix}/attestations` });
  await app.register(widgetRoutes, { prefix: `${prefix}/widget` });
  await app.register(goalsRoutes, { prefix: `${prefix}/goals` });
  await app.register(syncRoutes, { prefix: `${prefix}/sync` });
  await app.register(partnerRoutes, { prefix: `${prefix}/partners` });
  await app.register(notificationRoutes, { prefix: `${prefix}/notifications` });
  await app.register(identityRoutes, { prefix: `${prefix}/identity` });
  await app.register(benchmarkRoutes, { prefix: `${prefix}/benchmark` });
  await app.register(negotiateRoutes, { prefix: `${prefix}/negotiate` });
  await app.register(wrappedRoutes, { prefix: `${prefix}/wrapped` });
}
